[package]
name = "lines"
version = "0.1.0"
authors = ["Jacob Zimmermann <ppa@jzimm.net>"]

[dependencies.gtk]
version = "0.4"
features = ["v3_18"]

[dependencies]
gio = "0.4"
cairo-rs = "0.4"
failure = "0.1"
failure_derive = "0.1"
rand = "0.4"
lazy_static = "1.0"